services:
  proxy:
    image: eclipse-temurin:17-jre-focal
    #entrypoint: /opt/app/proxyEntrypoint.sh
    working_dir: /opt/app/
    command: java -jar /opt/app/velocity-3.2.0-SNAPSHOT-252.jar
    ports:
      - "25565:25565"
    volumes:
      - ./proxy:/opt/app
    stdin_open: true
    tty: true
  lobby:
    image: eclipse-temurin:17-jre-focal
    working_dir: /opt/app/
    command: java -jar /opt/app/paper-1.19.4-516.jar
    expose:
      - 25565
    volumes:
      - ./lobby:/opt/app
    stdin_open: true
    tty: true
    depends_on:
      - proxy