services:
  proxy:
    image: ghcr.io/timystream/mjrt:17
    environment:
      - SERVERJAR=[ServerSoftwareFile]
      - ARGS=""
    ports:
      - "25565:25565"
    volumes:
      - ./[Your Server folder name]:/app
    stdin_open: true
    tty: true
    user: [your User ID]:[your groupID]
## User Server ##
  [your servername]:
    image: ghcr.io/timystream/mjrt:17
    environment:
      - SERVERJAR=[ServerSoftwareFile]
    expose:
      - 25565
    volumes:
      - ./[Your Server folder name]:/app
    stdin_open: true
    tty: true
    user: [your User ID]:[your groupID]
    depends_on:
      - proxy
